apiVersion: v1
kind: Service 
metadata: 
  name: superset 
spec:
  selector:
    name: superset
  type: NodePort
  ports: 
  - name: test-port
  port: 8080
  targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: superset
  labels:
    name: superset
spec: 
  containers:
  - image: amancevice/superset
  name: superset



